#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code
    expose:
      - 8000
#    ports: # Le forbidden backdoor
#      - "8000:8000"
    links:
      - redis:redis
    working_dir: /code/mysite
    command: python manage.py runserver 0.0.0.0:8000

  redis:
      image: redis:latest
      expose:
        - 6379

  caddy:
      image: caddy:latest
      depends_on:
        - web
      links:
        - web:web
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - $PWD/Caddyfile:/etc/caddy/Caddyfile
        - $PWD/mysite/static:/srv/static/
        - $PWD/mysite/media:/srv/media/
        - caddy_data:/data
        - caddy_config:/config

volumes:
   caddy_data:
   caddy_config: